const notesDAW = [
  {
    nom: 'Pau',
    cognoms: 'García Pérez',
    edat: 18,
    genere: 'Home',
    dataInscripcio: '2023-09-15',
    cursos: [
      {
        nom: 'DAW-MP6',
        professor: 'Pablo Ros',
        notes: {
          UF1: 8.5,
          UF2: 7.9,
          UF3: 8.2,
          UF4: 7.6,
          UF5: 8.8,
        },
        notaFinal: null,
      },
      {
        nom: 'DAW-MP7',
        professor: 'Hector Ortiz',
        notes: {
          UF1: 7.1,
          UF2: 6.9,
          UF3: 5.4,
          UF4: 4.7,
          UF5: 8.2,
        },
        notaFinal: null,
      },
    ],
  },
  {
    nom: 'Marc',
    cognoms: 'García López',
    edat: 19,
    genere: 'Home',
    dataInscripcio: '2023-09-17',
    cursos: [
      {
        nom: 'DAW-MP6',
        professor: 'Pablo Ros',
        notes: {
          UF1: 4.2,
          UF2: 3.5,
          UF3: 6.8,
          UF4: 2.1,
          UF5: 5.4,
        },
        notaFinal: null,
      },
      {
        nom: 'DAW-MP7',
        professor: 'Hector Ortiz',
        notes: {
          UF1: 5.9,
          UF2: 7.2,
          UF3: 4.6,
          UF4: 6.3,
          UF5: 4.7,
        },
        notaFinal: null,
      },
    ],
  },
  {
    nom: 'Laura',
    cognoms: 'Fernández Torres',
    edat: 18,
    genere: 'Dona',
    dataInscripcio: '2023-09-18',
    cursos: [
      {
        nom: 'DAW-MP6',
        professor: 'Pablo Ros',
        notes: {
          UF1: 9.5,
          UF2: 7.8,
          UF3: 8.2,
          UF4: 9.4,
          UF5: 8.8,
        },
        notaFinal: null,
      },
      {
        nom: 'DAW-MP7',
        professor: 'Hector Ortiz',
        notes: {
          UF1: 6.2,
          UF2: 5.7,
          UF3: 4.8,
          UF4: 7.3,
          UF5: 3.9,
        },
        notaFinal: null,
      },
    ],
  },
  {
    nom: 'Alex',
    cognoms: 'Rodríguez Pérez',
    edat: 17,
    genere: 'Home',
    dataInscripcio: '2023-09-19',
    cursos: [
      {
        nom: 'DAW-MP6',
        professor: 'Pablo Ros',
        notes: {
          UF1: 6.8,
          UF2: 4.5,
          UF3: 9.2,
          UF4: 5.7,
          UF5: 6.3,
        },
        notaFinal: null,
      },
      {
        nom: 'DAW-MP7',
        professor: 'Hector Ortiz',
        notes: {
          UF1: 7.2,
          UF2: 5.8,
          UF3: 8.5,
          UF4: 4.9,
          UF5: 7.1,
        },
        notaFinal: null,
      },
    ],
  },
  {
    nom: 'Carla',
    cognoms: 'Gómez Martí',
    edat: 20,
    genere: 'Dona',
    dataInscripcio: '2023-09-20',
    cursos: [
      {
        nom: 'DAW-MP6',
        professor: 'Pablo Ros',
        notes: {
          UF1: 4.8,
          UF2: 5.1,
          UF3: 6.7,
          UF4: 7.5,
          UF5: 7.9,
        },
        notaFinal: null,
      },
      {
        nom: 'DAW-MP7',
        professor: 'Hector Ortiz',
        notes: {
          UF1: 8.3,
          UF2: 7.7,
          UF3: 8.1,
          UF4: 6.5,
          UF5: 9.0,
        },
        notaFinal: null,
      },
    ],
  },
  {
    nom: 'Eduard',
    cognoms: 'Fernández Serra',
    edat: 21,
    genere: 'Home',
    dataInscripcio: '2023-09-22',
    cursos: [
      {
        nom: 'DAW-MP6',
        professor: 'Pablo Ros',
        notes: {
          UF1: 9.2,
          UF2: 9.5,
          UF3: 9.1,
          UF4: 8.7,
          UF5: 9.8,
        },
        notaFinal: null,
      },
      {
        nom: 'DAW-MP7',
        professor: 'Hector Ortiz',
        notes: {
          UF1: 8.6,
          UF2: 7.9,
          UF3: 8.3,
          UF4: 8.9,
          UF5: 8.1,
        },
        notaFinal: null,
      },
    ],
  },
  {
    nom: 'Clara',
    cognoms: 'Sánchez López',
    edat: 20,
    genere: 'Dona',
    dataInscripcio: '2023-09-23',
    cursos: [
      {
        nom: 'DAW-MP6',
        professor: 'Pablo Ros',
        notes: {
          UF1: 7.6,
          UF2: 7.3,
          UF3: 6.9,
          UF4: 8.2,
          UF5: 6.7,
        },
        notaFinal: null,
      },
      {
        nom: 'DAW-MP7',
        professor: 'Hector Ortiz',
        notes: {
          UF1: 6.5,
          UF2: 6.7,
          UF3: 7.2,
          UF4: 6.4,
          UF5: 6.8,
        },
        notaFinal: null,
      },
    ],
  },
  {
    nom: 'Marta',
    cognoms: 'Gómez Serra',
    edat: 22,
    genere: 'Dona',
    dataInscripcio: '2023-09-24',
    cursos: [
      {
        nom: 'DAW-MP6',
        professor: 'Pablo Ros',
        notes: {
          UF1: 8.5,
          UF2: 8.7,
          UF3: 7.9,
          UF4: 7.6,
          UF5: 8.0,
        },
        notaFinal: null,
      },
      {
        nom: 'DAW-MP7',
        professor: 'Hector Ortiz',
        notes: {
          UF1: 7.8,
          UF2: 8.3,
          UF3: 7.1,
          UF4: 7.7,
          UF5: 7.5,
        },
        notaFinal: null,
      },
    ],
  },
  {
    nom: 'Elena',
    cognoms: 'López Fernández',
    edat: 19,
    genere: 'Dona',
    dataInscripcio: '2023-09-25',
    cursos: [
      {
        nom: 'DAW-MP6',
        professor: 'Pablo Ros',
        notes: {
          UF1: 6.9,
          UF2: 7.2,
          UF3: 7.5,
          UF4: 7.1,
          UF5: 6.8,
        },
        notaFinal: null,
      },
      {
        nom: 'DAW-MP7',
        professor: 'Hector Ortiz',
        notes: {
          UF1: 6.8,
          UF2: 6.6,
          UF3: 6.9,
          UF4: 7.2,
          UF5: 6.7,
        },
        notaFinal: null,
      },
    ],
  },
];

module.exports = notesDAW;
